TRUNCATE TABLE ASSISTANCE RESTART IDENTITY CASCADE;
TRUNCATE TABLE POLICY RESTART IDENTITY CASCADE;
TRUNCATE TABLE POLICY RESTART IDENTITY CASCADE;
TRUNCATE TABLE POLICY_HISTORY RESTART IDENTITY CASCADE;